esphome:
  name: can-node-1
  friendly_name: CAN-Node-1
  includes:
    - custom_components/ADXL345.h
  libraries:
    - "Wire"
    - "SPI"
    - "Adafruit BusIO"
    - "Adafruit Unified Sensor"
    - "Adafruit ADXL345"

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://mrk-its/esphome-canopen@siim_k

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lbErYIwSj7b5wMZjk3VerMkludAnLN8tnPSRFGVFf5E="

ota:
  password: "0d8cf65ef3024ead3163d86da57e5444"

wifi:
  id: wifi_component
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Can-Node-1 Fallback Hotspot"
    password: "NvFyE6hvzshS"

canbus:
  - platform: esp32_can
    id: can_bus
    rx_pin: GPIO23
    tx_pin: GPIO19
    can_id: 0
    bit_rate: 125kbps

canopen:
  id: can_gate
  canbus_id: can_bus
  node_id: 1
  heartbeat_interval: 1s
  entities:
    - id: wifi_switch
      tpdo: 0
      index: 1
      
    - id: adxl_activity
      tpdo: 0
      index: 2

      
###ADXL345###
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true


custom_component:
  - lambda: |-
      auto adxl345 = new ADXL345Sensor();
      return {adxl345};
    components:
      - id: adxl345


binary_sensor:
  - platform: custom
    lambda: |-
      return {static_cast<ADXL345Sensor *>(id(adxl345))->activity};
    binary_sensors:
      - name: "Activity sensor ADXL345"
        id: adxl_activity
        icon: "mdi:motion"
        internal: true
        filters:
          - delayed_off: 5s 

switch:
  - platform: template
    name: wifi
    id: wifi_switch
    internal: true
    lambda: return !id(wifi_component).is_disabled();
    turn_on_action:
      - wifi.enable
    turn_off_action:
      - wifi.disable



    