esphome:
  name: can-node-2
  friendly_name: CAN-Node-2

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://mrk-its/esphome-canopen@siim_k

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1iyveUYDIgmAiYgIpSN9kAurSoLOzeAgqwSqSTw4xjk="

ota:
  password: "e611ab315166e3d90e32326ae84b298a"

wifi:
  id: wifi_component
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Can-Node-2 Fallback Hotspot"
    password: "oL6i34oLKWMQ"

canbus:
  - platform: esp32_can
    id: can_bus
    rx_pin: GPIO21
    tx_pin: GPIO22
    can_id: 0
    bit_rate: 125kbps

canopen:
  id: can_gate
  canbus_id: can_bus
  node_id: 2
  heartbeat_interval: 1s
  entities:
    - id: wifi_switch
      tpdo: 0
      index: 1
    - id: motion_sensor
      tpdo: 0
      index: 2
    
switch:
  - platform: template
    name: wifi
    id: wifi_switch
    internal: true
    lambda: return !id(wifi_component).is_disabled();
    turn_on_action:
      - wifi.enable
    turn_off_action:
      - wifi.disable

binary_sensor:
  - platform: gpio
    id: motion_sensor
    name: motion_sensor
    pin: GPIO17
    device_class: motion
    internal: true
